version: "3.8"
services:
  # Reverse proxy pour les docker nginx
  nginx_proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_HOST=localhost
    ports:
      - 8080:80
  # dockers ngingx : 4 images répliquées gérées par le reverse proxy
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 4
